import { SDKAutoProvider } from "@repo/sdk/react";
import { QueryProvider } from "@repo/shared/presentation/providers/query-client-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SDKAutoProvider
          apiUrl={process.env.NEXT_PUBLIC_API_URL || "http://localhost:4100"}
        >
          <QueryProvider>{children}</QueryProvider>
        </SDKAutoProvider>
      </body>
    </html>
  );
}
