name: Docs Build

on:
  push:
    branches: [master, dev]
    paths:
      - 'apps/docs/**'
  pull_request:
    branches: [master, dev]
    paths:
      - 'apps/docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        working-directory: ./apps/docs
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: ./apps/docs
        run: yarn build
